[package]
edition = "2021"
name = "gui"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli = {path = "../cli"}
core = {path = "../core"}
eframe = "0.16.0"
image = "0.23.14"
rfd = "0.6.4"
